version: '3'

services:
  app:
    container_name: ExpenElixir
    image: basharherbawi/expenelixir:latest
    environment:
      - PORT=80
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "2077:80"
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      timeout: 20s
      retries: 5
    restart: always