version: '3'

services:
  app:
    profiles:
      - ExpenElixir
    container_name: ExpenElixir
    build: .
    environment:
      - PORT=80
      - DB_HOST=process.env.DB_HOST
      - DB_USER=process.env.DB_USER_NAME
      - DB_PASSWORD=process.env.DB_PASSWORD
      - DB_NAME=process.env.DB_NAME
    ports:
      - "2077:80"
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      timeout: 20s
      retries: 5
    restart: always