name: Build Docker Image and Deploy to EC2 Instance

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    concurrency: build-docker
    outputs:
      image_version: ${{ steps.image_version.outputs.githash }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup docker build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:${{ steps.image_version.outputs.githash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-image:
    needs: build-image
    uses: ./.github/workflows/deploy.yml
    with:
      instance_ip: ${{ vars.INSTANCE_IP }}
      image_version: ${{ needs.build-image.outputs.image_version }}
    secrets: inherit
