name: deploy docker

on:
  workflow_call:
    inputs:
      instance_ip:
        type: string
        required: true
      image_version:
        type: string
        required: true
  repository_dispatch:
    types: [deploy_event]

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-docker-expenelixir
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
          host: ${{ github.event.client_payload.ip }}
          user: github

      - name: deploy
        run: |
          sleep 100
          echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
          chmod 600 key.pem
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest
          docker run --name ExpenElixirX -d -p 80:2077 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USER_NAME=${{ secrets.DB_USER_NAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e FREE_CURRENCY_API=${{ secrets.FREE_CURRENCY_API }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            -e CHATGPTAPI_SECRET_KEY=${{ secrets.CHATGPTAPI_SECRET_KEY }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
