name: deploy docker

on:
  workflow_call:
    inputs:
      instance_ip:
        type: string
        required: true
      image_version:
        type: string
        required: true
  repository_dispatch:
    types: [deploy_event]

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-docker-expenelixir
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          host: ${{ github.event.client_payload.ip }}
          user: github

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: deploy
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME}}/expenelixir:${{ github.event.client_payload.image_version }}
          docker compose --file docker-compose-prod.yml up -d --remove-orphans
          docker system prune -af
