name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir

    - name: Set Environment Variables
      run: |
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"
        echo "DB_USER_NAME: $DB_USER_NAME"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "DB_NAME: $DB_NAME"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Get EC2 Instances IPs
      run: |
        public_ips=$(aws autoscaling describe-auto-scaling-instances --region eu-west-2 --output text \
        --query "AutoScalingInstances[?AutoScalingGroupName=='ExpenElixir-ASG'].InstanceId" \
        | xargs -n1 aws ec2 describe-instances --instance-ids $ID --region eu-west-2 \
        --query "Reservations[].Instances[].PublicIpAddress" --output text)
        echo "Public IPs: $public_ips"
    
    - name: Deploy to EC2 instances
      run: |
        echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
        chmod 600 key.pem
        for ip in $public_ips; do
          ssh -i 'key.pem' -o StrictHostKeyChecking=no github@$ip "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest"
          echo "Deployed to $ip"
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}

    # - name: Deployment
    #   run: |
    #     echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
    #     chmod 600 key.pem
    #     ssh -i 'key.pem' -o StrictHostKeyChecking=no github@${{secrets.EC2_IP}} 'docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest'
    #   env:
    #     DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}