# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   repository_dispatch:
#     types: [deploy_event]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Login to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Build and push the Docker image
#       run: |
#         docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir
#         docker push ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir

    - name: Set Environment Variables
      run: |
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"
        echo "DB_USER_NAME: $DB_USER_NAME"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "DB_NAME: $DB_NAME"

    - name: Deployment
      run: |
        echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -i 'key.pem' -o StrictHostKeyChecking=no github@${{secrets.EC2_IP}} 'docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest'
      env:
        DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}