name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir

    - name: Set Environment Variables
      run: |
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"
        echo "DB_USER_NAME: $DB_USER_NAME"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "DB_NAME: $DB_NAME"

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Get list of EC2 instances IPs from ASG
      run: |
        set -x
        instance_ids=$(aws ec2 describe-instances --query 'Reservations[].Instances[?Tags[?Key==`aws:autoscaling:groupName`].Value==`ExpenElixir-ASG`].[InstanceId]')
        echo "Instance IDs: $instance_ids"
        instance_ids=$(echo $instance_ids | jq -r '.[]')
        public_ips=""
        for id in $instance_ids; do
          ip=$(aws ec2 describe-instances --instance-ids $id --query 'Reservations[].Instances[].PublicIpAddress')
          echo "IP for $id: $ip"
          public_ips+="$ip "
        done
        echo "Public IPs: $public_ips"
    
    - name: Deploy to EC2 instances
      run: |
        for ip in $public_ips; do
          ssh -i 'key.pem' -o StrictHostKeyChecking=no ubuntu@$ip 'docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest'
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}

    # - name: Deployment
    #   run: |
    #     echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
    #     chmod 600 key.pem
    #     ssh -i 'key.pem' -o StrictHostKeyChecking=no github@${{secrets.EC2_IP}} 'docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 ${{ secrets.DOCKERHUB_USERNAME }}/expenelixir:latest'
    #   env:
    #     DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}