name: Docker CI & EC2 Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag basharherbawi/expenelixir:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push basharherbawi/expenelixir:latest

    - name: Prepare SSH Key
      run: |
        echo "${{ secrets.DEPLOYMENT_KEY }}" > deploy_key
        chmod 600 deploy_key
        ssh-keyscan 18.132.1.139 >> known_hosts

    - name: SSH & Deploy Docker Container on EC2
      run: |
        scp -i deploy_key Dockerfile github@18.132.1.139:~/Dockerfile
        ssh -i deploy_key github@18.132.1.139 "docker pull basharherbawi/expenelixir:latest && docker run --name ExpenElixirX -d -p 80:2077 basharherbawi/expenelixir:latest"
