name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag basharherbawi/expenelixir
        docker push basharherbawi/expenelixir
    
    - name: Deployment
      run: |
        echo "${{ secrets.DEPLOYMENT_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -i 'key.pem' github@18.132.1.139 echo "Connected successfully"
      env:
        DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}
