name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag basharherbawi/expenelixir
        docker push basharherbawi/expenelixir
    
    - name: Configure Docker Host on EC2
      uses: khaledez/configure-docker-host@v1
      with:
        host: 18.132.1.139
        user: github
        ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}

    - name: Deploy on EC2
      run: |
        docker pull basharherbawi/expenelixir:latest
        docker run --name ExpenElixirX -d -p 80:2077 basharherbawi/expenelixir:latest
