name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag basharherbawi/expenelixir
        docker push basharherbawi/expenelixir

    - name: Setup SSH for deployment
      run: |
        echo "${{ secrets.DEPLOYMENT_KEY }}" > deploy_key
        echo "Debugging (first 10 characters): ${DEPLOYMENT_PRIVATE_KEY:0:10}" # This line attempts to display the first 10 characters.
        chmod 600 deploy_key
        ssh-keyscan 18.132.1.139 >> known_hosts
        ssh -i deploy_key github@18.132.1.139 'docker pull basharherbawi/expenelixir && docker run --name ExpenElixirX -d -p 80:2077 basharherbawi/expenelixir:latest'

      env:
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
